<h1>Kontaktní formulář</h1>

<p>Kontaktujte nás odesláním formuláře níže.</p>

<form method="post">
	<div class="form-group">
		<label for="email">Email address</label>
		<input id="email" type="email" name="email" class="form-control" required="required" value="<?php if (isset($_POST['email'])) echo(htmlspecialchars($_POST['email'])); ?>" />
	</div>
	<div class="form-group">
		<label for="firstname">First name</label>
		<input id="firstname" type="name" name="firstname" class="form-control" required="required" value="<?php if (isset($_POST['firstname'])) echo(htmlspecialchars($_POST['firstname'])); ?>" />
	</div>
	<div class="form-group">
		<label for="lastname">Last name</label>
		<input id="lastname" type="name" name="lastname" class="form-control" required="required" value="<?php if (isset($_POST['lastname'])) echo(htmlspecialchars($_POST['lastname'])); ?>" />
	</div>
	<div class="form-group">
		<label for="message">Your message</label>
		<textarea id="message" name="message" class="form-control"><?php if (isset($_POST['message'])) echo(htmlspecialchars($_POST['message'])); ?></textarea>
	</div>
	<input type="submit" class="btn btn-primary" value="Submit" />
</form>