<h1>Přihlášení do administrace</h1>

<form method="post">
	<div class="form-group">
		<label for="login">Login</label>
		<input id="login" type="text" name="login" class="form-control" />
	</div>
	<div class="form-group">
		<label for="password">Password</label>
		<input id="password" type="password" name="password" class="form-control"/>
	</div>

	<input type="submit" class="btn btn-primary" value="Login" />
</form>

<p>Pokud ještě nemáte účet, <a href="registrace">zaregistrujte se</a>.</p>