<h1>Edit article</h1>

<form method="post">
<input type="hidden" name="id_article" value="<?= $article['id_article'] ?>" />
<div class="form-group">
	<label for="title">Title</label>
	<input type="text" name="title" value="<?= $article['title'] ?>" class="form-control"/>
</div>
<div class="form-group">
	<label for="url">URL</label>
	<input type="text" name="url" value="<?= $article['url'] ?>" class="form-control" />
</div>
<div class="form-group">
	<label for="description">Description</label>
	<input type="text" name="description" value="<?= $article['description'] ?>" class="form-control" />
</div>
<div class="form-group">
	<label for="key_words">Key Words</label>
	<input type="text" name="key_words" value="<?= $article['key_words'] ?>" class="form-control" />
</div>
<div class="form-group">
	<label for="category">Category</label>
	<select name="id_article_category" class="form-control">
		<?php foreach ($categories as $category) : ?>
			<option value="<?= $category['id_article_category'] ?>"
			
			<?php if ($article['id_article_category'] == $category['id_article_category']) : ?>
			selected
			<?php endif ?>

			><?= $category['name'] ?></option>
		<?php endforeach ?>
	</select>
</div>

	
	   


	<?php log_as_json($categories) ?>

	<textarea name="content"><?= $article['content'] ?></textarea>
<div class="form-group">
	<input type="submit" class="btn btn-primary" value="Save article" />
</div>

</form>

<script type="text/javascript" src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script type="text/javascript">
	tinymce.init({
			selector: "textarea[name=content]",
			plugins: [
					"advlist autolink lists link image charmap print preview anchor",
					"searchreplace visualblocks code fullscreen",
					"insertdatetime media table contextmenu paste"
			],
			toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
			entities: "160,nbsp",
			entity_encoding: "named",
			entity_encoding: "raw"
	});
</script>